# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='colum',
            new_name='column',
        ),
    ]
